---
- name: Run CLAB
  hosts: localhost
  become: yes
  become_method: sudo
  gather_facts: false
  vars:
    ansible_become_password: password
    topology_file: /home/user1/actions-runner/_work/ceos_config/ceos_config/containerlab_test/topology.clab.yaml
  tasks:   
   - name: Execute destroy
     local_action: command sudo containerlab destroy --topo {{ topology_file }}
     become: yes
     register: destroy_out
     ignore_errors: true
   
   - debug: msg="{{ destroy_out }}"