---
- name: cEOS Config
  hosts: ceos
  gather_facts: no
  tasks:
    - name: Retrieve VLAN configuration
      eos_command:
        commands: show vlan
      register: vlan_output

    - name: Check if specific VLAN is present
      set_fact:
        vlan_present: "{{ 'VLAN0010' in vlan_output.stdout[0] }}"

    - name: Fail if VLAN is not present
      fail:
        msg: "VLAN 10 is not present on the switch."
      when: not vlan_present

    - name: Debug message if VLAN is present
      debug:
        msg: "VLAN 10 is present on the switch."
      when: vlan_present